
networks:
  edge:
    driver: bridge

services:
  # ---------------------------
  # Réplica 1 do app
  # ---------------------------
  web1:
    image: darlon/iftech:webcontador
    container_name: iftech-webcontador-1
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    expose:
      - "8000"
    networks: [edge]
    labels:
      - traefik.enable=true
      - traefik.http.services.iftech.loadbalancer.server.port=8000
      - traefik.http.services.iftech.loadbalancer.sticky.cookie=true
      - com.centurylinklabs.watchtower.enable=true

  # ---------------------------
  # Réplica 2 do app
  # ---------------------------
  web2:
    image: darlon/iftech:webcontador
    container_name: iftech-webcontador-2
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    expose:
      - "8000"
    networks: [edge]
    labels:
      - traefik.enable=true
      - traefik.http.services.iftech.loadbalancer.server.port=8000
      - traefik.http.services.iftech.loadbalancer.sticky.cookie=true
      - com.centurylinklabs.watchtower.enable=true

  # ---------------------------
  # Traefik
  # ---------------------------
  traefik:
    image: traefik:v2.11
    container_name: iftech-traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/etc/traefik/dynamic.yml   # <--- ADICIONE ESTA LINHA
      - --entrypoints.web.address=:80
    networks: [edge]
    expose:
      - "80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # ---------------------------
  # Cloudflare Tunnel (via token)
  # ---------------------------
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: iftech-cloudflared
    restart: unless-stopped
    depends_on:
      - traefik
    networks: [edge]
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # ---------------------------
  # Watchtower
  # ---------------------------
  watchtower:
    image: containrrr/watchtower
    container_name: iftech-watchtower
    restart: unless-stopped
    networks: [edge]
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
